### ISSUE TITLE
Duplicate programs cause error on PA save

### ISSUE THREAD

**Issue by glind** [mercycorps/tola-activity#167]
ksandstrom@mercycorps.org User's who have access to multiple countries may see duplicate programs. If they try and save a PA to one of the duplicate programs, they will receive the following JSON error. 
Example of a Duplicate Program:
GAITID: 6514 Toys for Busma Centers in Lebanon
Listed twice for a user who has access to Lebanon and Pakistan country programs in their Activtiy Profile
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
MultipleObjectsReturned at /activitydb/projectagreement_update/220/
get() returned more than one Program -- it returned 2!
Request Method:	POST
Request URL:	https://tola-activity-demo.mercycorps.org/activitydb/projectagreement_update/220/
Django Version:	1.8.2
Exception Type:	MultipleObjectsReturned
Exception Value:	
get() returned more than one Program -- it returned 2!
Exception Location:	/usr/local/lib/python2.7/site-packages/django/db/models/query.py in get, line 338
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages',
 '/var/www/tola-activity/htdocs',
 '/var/www/tola-activity/htdocs/tola',
 '/var/www/tola-activity/htdocs']
Server time:	Tue, 17 Nov 2015 11:30:40 -0800

**Comment by glind** [comment]
This is a bit confusing.  The duplicate programs should not affect a project because you should only be able to select one program to a project.  That's the error thrown is on getting a program for the submitted project, that would mean somehow a project had more then one program and that relationship is not allowed int he data base.  Can we double check this with another project?  The one above seems to work fine in production and on demo. project_id = 220.

https://tola-activity-demo.mercycorps.org/activitydb/projectagreement_update/220/

**Comment by karrla** [comment]
The user must have access to multiple countries in their profile. 

I added the following to my profile: 
AF, CN, ET, HT, ID, IQ, JO, KE, LB, LR, ML, MN, PH, PK, SO, US
And (Example) GAITID: 6514 Toys for Busma Centers in Lebanon (it shows up twice)
I created these PAs 
https://tola-activity-demo.mercycorps.org/activitydb/projectagreement_update/668/
https://tola-activity-demo.mercycorps.org/activitydb/projectagreement_update/667/
And when I try to save the PA there is an  Exception Value of:	get() returned more than one Program -- it returned 2!  

Please add multiple countries to your Profile and then retry with the above two PAs  668 and 667

**Comment by glind** [comment]
Yeah something weird going on, look at the agreement you send... They don't have programs selected and that is a required field.   How did you submit those without filling out choosing a program?

**Comment by glind** [comment]
I don't doubt that programs will show up twice but that should affect the PA because you have to choose a single program when you create a project.

**Comment by karrla** [comment]
I don't think this is crtitcal bug, as most users will not have multiple countries, but I can repeat it. 
It matters which countries I have in my Profile. The two countries in this case that cause issues is PK and LB along with the program: GAITID: 6514 Toys for Busma Centers in Lebanon 

If I have PK and LB I get the exceptinon: get() returned more than one Program -- it returned 2!

If I remove PK from my list of countries, but leave all the rest I get the exception: 'NoneType' object has no attribute 'append'

If I remove LB from the list, the Program is no longer listed in the Exec.Summary and I can't save it, because there is no Program in the PA

If I add ONLY LB to my profile, I can successfully save it.

**Comment by glind** [comment]
It is somewhat critical because while having two countries created the error, that's not actually the real problem.  The issue is being able to create a project with TWO or ZERO programs associated with it as you were somehow able to do.  That should not be allowed because it is a required field and it's Foreign Key relationship in the database only allows 1 as well as requires 1.  So what I really want to know is how you were able to do that, because I can't replicate that.

**Comment by karrla** [comment]
Senario One: 
1. Login >  Go to your Profile >  Add PK and LB to your "Accessible Countries."
2. Workflow > Program Dashboard > From the Dropdown of Programs, notice 6514 is listed twice
3. Click Create Project > Select one of the Program 6514 which is called: Toys for Busma Centers in Lebanon > Name your Project and Submit 
4. Click Update Progarm Agreement  (make note of the URL of the PA for Senario  2 since the country will not have accesss to the PA in their Program Dashboard) 
5. Save: You should receive the exception: it returned 2!

Senario Two (Program Not Present)
Profile:  remove LB  and add TL only
Now go to the URL of the PA you created in Step One
You can access the PA, but the Program is not present 

Senario Three 
Profile: add LB and keep TL 
Now go to the URL of the PA you created in Step One
and click SAVE 
You should receive the exception: 'NoneType' object has no attribute 'append'

Senario  Four 
Profile: LB only
Now go to the URL of the PA you created in Step One
You can access the PA and Save it. 

Senario  Five
Profile:  PK only  
Now go to the URL of the PA you created in Step One
You can access the PA and Save it.

**Comment by glind** [comment]
Ah, that's the difference.  2 programs with the same name available in the drop down.  That should not happen.  Ok thanks I will look into that.
